[env]
RUST_BACKTRACE = { value = "full", force = true }

[target.x86_64-unknown-linux-musl]
rustflags = "-Ctarget-feature=-crt-static"

[target.aarch64-unknown-linux-musl]
rustflags = "-Ctarget-feature=-crt-static"